### ISSUE TITLE
[BUG] Failed to load the dec-hex-oct-bin package

### ISSUE THREAD

**Issue by bluebruce** [atom-extensions/dec-hex-oct-bin#4] opened 2015-11-03 16:57 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [dec-hex-oct-bin](https://github.com/erkkikeranen/dec-hex-oct-bin) package, v0.1.1
### Stack Trace

Failed to load the dec-hex-oct-bin package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/bruce/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:1:1)
  at /Users/bruce/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:6:3
  at Object.<anonymous> (/Users/bruce/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:171:5)
  at Object.<anonymous> (/Users/bruce/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/bruce/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin.coffee:1:20)
  at Object.<anonymous> (/Users/bruce/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:725:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:176:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:473:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```
### Commands

```
     -7:51.8.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -7:50 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:50 sync-settings:backup (atom-text-editor.editor.mini)
     -7:07.4.0 line-ending-converter-list-view:show (atom-text-editor.editor)
     -7:05.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:05.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
 21x -4:25.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:23 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -4:19.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:19.4.0 sync-settings:backup (atom-text-editor.editor.mini)
  6x -3:40.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -3:38 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "useReactEditor": true,
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "goto",
      "atom-beautify",
      "symbols-view",
      "ctags-status",
      "git-history",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "minimap",
      "symbol-gen",
      "line-ending-selector"
    ],
    "packagesWithKeymapsDisabled": [
      "symbols-view",
      "column-select"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v4.4.0
autocomplete-ctags, v0.3.2
column-select, v0.2.0
cursor-history, v0.5.6
dec-hex-oct-bin, v0.1.1
deprecation-cop, v0.54.0
disable-keybindings, v0.5.0
file-icons, v1.6.11
highlight-column, v0.5.0
highlight-line, v0.11.0
language-go, v0.39.0
language-perl, v0.30.0
language-ruby, v0.60.0
language-ruby-on-rails, v0.23.0
language-toml, v0.16.0
line-ending-converter, v1.3.2
metrics, v0.53.0
open-recent, v4.0.1
selection-highlight, v0.1.4
symbols-tree-view, v0.10.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by drbullit** [comment] 2016-03-04 21:28
Same problem here!

**Comment by itpropro** [comment] 2016-03-16 23:07
Same problem on Windows 10 x64

**Comment by sangio90** [comment] 2016-03-17 13:24
same problem on OSX10.11.3

**Comment by magnusart** [comment] 2016-03-29 21:25
Same problem on El Captian. Removing plugin since it is not usable (will not start).

**Comment by slonak79** [comment] 2017-05-13 19:13
same issue here.

**Comment by enigmaticlilit** [comment] 2017-08-26 10:06
Same problem.

**Comment by eMedus** [comment] 2017-12-13 17:09
Same issue with Windows 8 and MacOS X High Sierra.

**Comment by elec3647** [comment] 2018-07-21 14:57
Same issue on MacOs 10.13.6 (17G65)

**Comment by vivi90** [comment] 2020-07-31 12:19
Same here:
### Steps to reproduce:
Just try to install the package.

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: "Manjaro Linux"
**Thrown From**: [dec-hex-oct-bin](https://github.com/erkkikeranen/dec-hex-oct-bin) package 0.1.1

### Stack Trace
Failed to load the dec-hex-oct-bin package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:1:1)
    at /packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:6:3
    at /packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:90:18)
    at /packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:1:1)
    at /packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/dec-hex-oct-bin/lib/dec-hex-oct-bin.coffee:1:20)
    at /packages/dec-hex-oct-bin/lib/dec-hex-oct-bin.coffee:1:1)
    at /packages/dec-hex-oct-bin/lib/dec-hex-oct-bin.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Package.requireMainModule (/usr/lib/atom/src/package.js:907:27)
    at /usr/lib/atom/src/package.js:140:16
    at Package.measure (/usr/lib/atom/src/package.js:81:19)
    at Package.load (/usr/lib/atom/src/package.js:126:10)
    at PackageManager.loadAvailablePackage (/usr/lib/atom/src/package-manager.js:711:10)
    at /usr/lib/atom/src/package-manager.js:607:14
    at Config.transact (/usr/lib/atom/src/config.js:892:14)
    at PackageManager.loadPackages (/usr/lib/atom/src/package-manager.js:605:17)
```

### Commands

```
```

### Non-Core Packages

```
ascii-hex 0.2.0 
atom-alignment 0.13.0 
atom-ide-terminal 5.0.1 
atom-ide-ui 0.13.0 
atom-music 1.0.2 
atom-ternjs 0.20.0 
atom-typing-speedometer 0.3.1 
audio 1.5.7 
autocomplete-java 1.2.7 
autocomplete-javascript 0.0.2 
autocomplete-python 1.16.0 
autocomplete-sql 0.5.0 
busy-signal 2.0.1 
character-table 0.4.3 
code-stats-atom 2.0.6 
color-picker 2.3.0 
cson 2.0.1 
dec-hex-oct-bin 0.1.1 
editor-background 1.2.42 
file-icons 2.1.42 
highlight-selected 0.17.0 
hyperclick 0.0.0 
ide-cpp 0.1.0 
ide-java 0.9.0 
ide-php 0.7.18 
intentions 1.1.5 
java-generator 2.2.3 
kite 0.185.0 
language-assembly 0.7.2 
language-haskell 1.20.0 
language-latex 1.2.0 
language-lsl 2.2.0 
language-vhdl 0.7.2 
latex 0.50.2 
latexer 0.3.0 
linter-javac 1.10.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-lens 0.7.0 
minimap-pigments 0.2.2 
pandoc-convert 1.1.1 
pdf-view 0.72.0 
php-ide-serenata 5.3.0 
pigments 0.40.2 
plantuml-toolkit 0.2.0 
project-manager 3.3.8 
quick-query 1.1.1 
quick-query-sqlite 0.3.2 
rcrsv-dark-ui 0.5.0 
sync-settings 4.3.8 
teletype 0.13.4 
tree-view-filter 0.5.5 
videoplayer 1.5.1 
xilinx-unisims 0.1.0 
zip-folder 3.3.0 
```

**Comment by vivi90** [comment] 2020-08-01 11:41
Duplicate of: https://github.com/atom-extensions/dec-hex-oct-bin/issues/2

**Closed by vivi90** 2020-08-01 11:41 UTC
Labels: bug, critical, duplicate
