### ISSUE TITLE
[BUG] Failed to activate the dec-hex-oct-bin package

### ISSUE THREAD

**Issue by miikeFuhrer** [atom-extensions/dec-hex-oct-bin#3] opened 2015-09-23 00:40 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [dec-hex-oct-bin](https://github.com/erkkikeranen/dec-hex-oct-bin) package, v0.1.1
### Stack Trace

Failed to activate the dec-hex-oct-bin package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/Blumonpay/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:1:1)
  at /Users/Blumonpay/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:6:3
  at Object.<anonymous> (/Users/Blumonpay/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:171:5)
  at Object.<anonymous> (/Users/Blumonpay/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/Blumonpay/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin.coffee:1:20)
  at Object.<anonymous> (/Users/Blumonpay/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:263:14)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:241:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:838:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
     -0:18.2.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:17.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:16.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:09.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:07.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.2.0 core:undo (atom-text-editor.editor.is-focused)
     -0:00.7.0 dec-hex-oct-bin:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.12
dec-hex-oct-bin, v0.1.1
emmet, v2.3.12

# Dev
No dev packages
```

**Comment by vivi90** [comment] 2020-08-01 11:42
Duplicate of: https://github.com/atom-extensions/dec-hex-oct-bin/issues/2

**Closed by vivi90** 2020-08-01 11:42 UTC
Labels: bug, critical, duplicate
